config/routes.rb
DevchixRails2Rc::Application.routes.draw do
  resources :profiles

  devise_for :users

  root :to => "home#index"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  cattr_reader :per_page
  @@per_page = 20

  def name
    self.first_name + " " + self.last_name
  end

  def self.search(search_field, search_value)  
    if search_field == "name"  
      where('first_name LIKE ? or last_name LIKE ?', "%#{search_value}%", "%#{search_value}%")  
    elsif search_field == "location"  
      where('location LIKE ?', "%#{search_value}%")  
    else  
      scoped  
    end  
  end  

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  has_one :profile, :dependent => :destroy 
  after_create :build_profile

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation

   # so users can login by email or username, not tested yet
   # to look up a user by email or username
   def self.find_for_authentication(conditions={})
    if conditions[:login] =~ /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i # email regex
      conditions[:email] = conditions[:login]
      conditions.delete("login")
    end
    super
  end
  
  private
  def build_profile
    # tried using self.build_profile but didn't work. Meh. moving on
    self.profile = Profile.new
    self.profile.save(:validate => false) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  respond_to :html
  helper_method :sort_column, :sort_direction  
  before_filter :authenticate_user!

  # GET /profiles
  # GET /profiles.xml
  def index
    if params[:search_name] != "name" && !params[:search_name].blank?
      field = "name"
      value = params[:search_name]
    elsif params[:search_location] != "name" && !params[:search_location].blank?
      field = "location"
      value = params[:search_location]
    end
    @profiles = Profile.search(field, value).order(sort_column + ' ' + sort_direction).paginate(:per_page => 20, :page => params[:page])
    respond_with(@profiles)
  end

  # GET /profiles/1
  # GET /profiles/1.xml
  def show
    @profile = Profile.find_by_user_id(params[:id])

  rescue ActiveRecord::RecordNotFound => e
    Rails.logger.info("Tried to access profile id #{params[:id]} and was not found")
    flash[:notice] = "You are not authorized to modify that profile"
    redirect_to root_path
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
    # Wanted to raise exception of not authorized, but i don't know what its called. for now
    # using the AR one.
    raise ActiveRecord::RecordNotFound unless @profile.user_id == current_user[:id] #or admin
  rescue ActiveRecord::RecordNotFound => e
    Rails.logger.info("Tried to access profile id #{params[:id]} and was not found")
    flash[:notice] = "You are not authorized to modify that profile"
    redirect_to root_path
  end

  # PUT /profiles/1
  def update
    @profile = Profile.find(params[:id])

    if @profile.update_attributes(params[:profile])
      flash[:notice] = 'Profile was successfully updated.'
    end
    respond_with(@profile, :location => profiles_url)
  end

  private  
  def sort_column  
    params[:sort] || "last_name"  
  end  
     
  def sort_direction  
    params[:direction] || "asc"  
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)  
    title ||= column.titleize  
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil  
    direction = (column == sort_column && sort_direction ==  "asc") ? "desc" : "asc"  
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}  
  end  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def full_name(profile) 
   "#{profile.first_name} #{profile.last_name}"
  end

end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      DevChix
    = stylesheet_link_tag 'reset', '960','text', 'application'
 
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.js', 'application'
    = csrf_meta_tag 

  %body
    #header
      .container_16.clearfix
        #headline
        #menu
          .grid_10.alpha
            =link_to "Home", root_url
            - if user_signed_in?
              |
              =link_to "My Profile", profile_path(current_user[:id])
              |
              =link_to "Users", profiles_url
              |
              =link_to  'Logout', destroy_user_session_url
          .grid_5.omega.logged_in_as
            - if user_signed_in?
              Logged in as:&nbsp;
              =current_user.email
            - else 
              =link_to  'Login', user_session_path
              | 
              =link_to  'Sign Up', new_user_registration_path
    #flash
      #flash_content.container_16.clearfix
        .grid_16
          %span{:style => "color: green"}
            =flash[:notice]
          %span{:style => "color: red"}
            =flash[:alert] 
    #main
      #content.container_16.clearfix
        .grid_16
          =yield
    #footer
      #footer_content.container_16
        %p
          &copy;DevChix 2010

app/views/profiles/_form.html.haml
= form_for @profile do |f|
  -if @profile.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      %ul
        - @profile.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :bio
    = f.text_area :bio
  .field
    = f.label :birthday
    = f.date_select :birthday
  .field
    = f.label :linkedin
    = f.text_field :linkedin
  .field
    = f.label :twitter
    = f.text_field :twitter
  .field
    = f.label :facebook
    = f.text_field :facebook
    .actions
    = f.submit 'Save'

app/views/profiles/_profile.html.haml
%tr
	%td 
		=profile.first_name
	%td 
		=profile.country
	%td 
		=profile.location

app/views/profiles/edit.html.haml
%h1 Editing profile

= render 'form'

= link_to 'Show', @profile
\|
= link_to 'Back', profiles_path

app/views/profiles/index.html.haml
%h1 Listing profiles

= form_tag profiles_path, :method => 'get', :id => 'search_form' do 
  %p
    = hidden_field_tag :direction, params[:direction] 
    = hidden_field_tag :sort, params[:sort] 
    = text_field_tag :search_name, params[:search_name], {:id => 'name_search',:value => 'name', :class => 'greyed'} 
    = text_field_tag :search_location, params[:search_location], {:id => 'location_search',:value => 'location', :class => 'greyed'} 
    = submit_tag "Search", :name => nil 
    %a{:href => "/profiles"}
      Start Over

= will_paginate @posts

%table
  %tr
    %th 
      = sortable('last_name', 'Name')
    %th
      = sortable('country')
    %th
      = sortable('location')
  #products
    = render @profiles

%br

app/views/profiles/new.html.haml
%h1 New profile

= render 'form'

= link_to 'Back', profiles_path

app/views/profiles/show.html.haml
%p
%p
  %b First name:
  = @profile.first_name
%p
  %b Last name:
  = @profile.last_name
%p
  %b Country:
  = @profile.country
%p
  %b Location:
  = @profile.location
%p
  %b Bio:
  = @profile.bio
%p
  %b Birthday:
  = @profile.birthday

= link_to 'Edit', edit_profile_path(@profile)